-- HISTORICAL NOTE ONLY (NON-EXECUTABLE)
-- This file is intentionally kept as an archive reference.
--
-- IMPORTANT:
--   Do NOT apply this file to any environment.
--   Canonical source of truth is:
--     - supabase/migrations/
--     - database/migrations/
--
-- Why this exists:
--   This legacy script previously contained ad-hoc function definitions
--   and caused migration drift between environments.
--
-- Status:
--   Replaced by versioned migrations on 2026-03-21.
