// Catálogo de productos -> frase en inglés para el generador de imágenes.
// Fuente: flutter_client/lib/features/shopping/utils/shopping_localization.dart
// La "key" debe coincidir EXACTO con la del catálogo (así el manifest matchea).
// El "noun" es la descripción del objeto a dibujar (afinada para items argentinos).

const catalog = [
  ['tomato', 'a ripe red tomato'],
  ['onion', 'a brown onion'],
  ['greenOnion', 'a bunch of green onions (scallions)'],
  ['potato', 'a potato'],
  ['apple', 'a red apple with a small green leaf'],
  ['banana', 'a ripe yellow banana'],
  ['pear', 'a green pear'],
  ['peach', 'a peach'],
  ['lemon', 'a yellow lemon with a leaf'],
  ['orange', 'an orange fruit with a leaf'],
  ['tangerine', 'a peeled-friendly mandarin orange'],
  ['grapefruit', 'a grapefruit cut showing pink flesh'],
  ['kiwi', 'a kiwi fruit sliced in half'],
  ['pineapple', 'a pineapple'],
  ['strawberry', 'a strawberry'],
  ['grapes', 'a bunch of purple grapes'],
  ['watermelon', 'a slice of watermelon'],
  ['carrot', 'a carrot with a bright natural orange body and green leafy top'],
  ['garlic', 'a head of garlic'],
  ['ginger', 'a ginger root'],
  ['lettuce', 'a head of green lettuce'],
  ['arugula', 'a small bunch of arugula leaves'],
  ['spinach', 'a bunch of spinach leaves'],
  ['chard', 'a bunch of swiss chard'],
  ['celery', 'a celery stalk bunch'],
  ['avocado', 'an avocado cut in half with the pit'],
  ['bellPepper', 'a red bell pepper'],
  ['pepper', 'a green chili pepper'],
  ['pumpkin', 'an orange pumpkin squash'],
  ['sweetPotato', 'a sweet potato'],
  ['boniato', 'a sweet potato'],
  ['broccoli', 'a broccoli floret'],
  ['eggplant', 'a purple eggplant'],
  ['mushrooms', 'two button mushrooms'],
  ['corn', 'an ear of corn with husk leaves'],
  ['cucumber', 'a cucumber'],
  ['beet', 'a red beetroot with leaves'],
  ['groundBeef', 'a fresh portion of ground beef mince on a small tray'],
  ['chicken', 'a cooked golden roast chicken drumstick, appetizing warm tones'],
  ['fish', 'a whole fresh fish with a bluish-silver body'],
  ['pork', 'a cut of fresh pink pork meat'],
  ['bondiola', 'a cut of pork shoulder meat'],
  ['flankSteak', 'a fresh cut of red beef steak'],
  ['matambre', 'a thin rolled beef cut tied with string'],
  ['peceto', 'a round beef roast cut'],
  ['ribs', 'a rack of beef ribs, appetizing cooked tones'],
  ['milanesas', 'a golden breaded meat cutlet (milanesa)'],
  ['sausages', 'a pair of plump sausages'],
  ['chorizo', 'a chorizo sausage'],
  ['burgers', 'two stacked burger patties'],
  ['bacon', 'a few strips of pink and red bacon'],
  ['milk', 'a milk carton with a clearly colored blue label and a colored cap'],
  ['plantMilk', 'a carton of plant-based milk with a green leaf and a colored label'],
  ['condensedMilk', 'an open can of condensed milk with a blue label'],
  ['chocolateMilk', 'a carton of chocolate milk with a brown label'],
  ['freshCheese', 'a block of fresh cheese with a soft yellow tone and a colored band'],
  ['gratedCheese', 'a bowl of grated cheese with a small pile in front'],
  ['creamCheese', 'a tub of cream cheese with a saturated colored lid'],
  ['provolone', 'a wheel of provolone cheese with a golden rind'],
  ['mozzarella', 'a ball of mozzarella cheese on a small dish'],
  ['butter', 'a stick of yellow butter on a small wrapper'],
  ['cream', 'a small carton of cream with a colored label'],
  ['yogurt', 'a yogurt cup with a peeled-back foil lid and a colored label'],
  ['drinkableYogurt', 'a bottle of drinkable yogurt with a colored label'],
  ['eggs', 'two eggs, one with a yolk'],
  ['dulceDeLeche', 'a jar of dulce de leche caramel spread with a colored lid'],
  ['tofu', 'a block of tofu with a soft colored accent'],
  ['hummus', 'a bowl of hummus with a colored rim'],
  ['bread', 'a whole rustic round loaf of crusty golden bread, uncut, no slices'],
  ['sandwichBread', 'a loaf of sliced sandwich bread with golden crust'],
  ['breadcrumbs', 'a bowl of golden breadcrumbs'],
  ['toast', 'two slices of golden toast'],
  ['croissants', 'two croissants'],
  ['criollos', 'criollo pastry biscuits'],
  ['biscuits', 'a stack of plain biscuits'],
  ['ladyfingers', 'ladyfinger biscuits'],
  ['cookies', 'a few round cookies'],
  ['tart', 'a savory tart pie'],
  ['detergent', 'a bottle of dish detergent'],
  ['bleach', 'a bottle of bleach'],
  ['glassCleaner', 'a spray bottle of glass cleaner'],
  ['floorCleaner', 'a bottle of floor cleaner'],
  ['multipurposeCleaner', 'a spray bottle of multi-purpose cleaner'],
  ['degreaser', 'a spray bottle of degreaser'],
  ['disinfectant', 'a bottle of disinfectant'],
  ['insecticide', 'an aerosol can of insecticide'],
  ['toiletPaper', 'a roll of toilet paper with a soft blue-grey shading'],
  ['kitchenRoll', 'a roll of paper towels with a colored band'],
  ['sponge', 'a two-tone cleaning sponge (yellow and green)'],
  ['dishcloth', 'a folded checkered cleaning cloth'],
  ['broom', 'a broom with a colored handle and golden bristles'],
  ['laundrySoap', 'a box of laundry detergent with a colored label'],
  ['softener', 'a bottle of fabric softener'],
  ['bags', 'a roll of plastic bags'],
  ['water', 'a clear water bottle with a colored cap and a hint of blue water'],
  ['flavoredWater', 'a bottle of flavored water with a colored label'],
  ['sparklingWater', 'a soda siphon bottle with a metal top'],
  ['tonicWater', 'a bottle of tonic water with a colored label'],
  ['soda', 'a bottle of soft drink soda'],
  ['cocaCola', 'a glass bottle of cola soft drink'],
  ['juice', 'a carton of fruit juice with a straw'],
  ['sportsDrink', 'a bottle of sports drink'],
  ['energyDrink', 'a can of energy drink'],
  ['beer', 'a bottle of beer'],
  ['wine', 'a bottle of red wine'],
  ['vermouth', 'a bottle of vermouth'],
  ['champagne', 'a bottle of champagne'],
  ['cider', 'a bottle of cider'],
  ['whisky', 'a bottle of whisky'],
  ['fernet', 'a dark bottle of fernet liquor'],
  ['aperitif', 'a glass of orange aperitif drink'],
  ['terma', 'a bottle of herbal bitters drink'],
  ['chips', 'an open bag of potato chips with a few golden chips spilling out in front'],
  ['cheesePuffs', 'a bag of cheese puff snacks'],
  ['pretzelSticks', 'a handful of salted pretzel sticks'],
  ['popcorn', 'a bucket of popcorn'],
  ['chocolate', 'a chocolate bar'],
  ['turron', 'a nougat bar'],
  ['alfajor', 'an alfajor round cookie sandwich'],
  ['poundCake', 'a slice of pound cake'],
  ['iceCream', 'an ice cream tub'],
  ['sweetCookies', 'a pack of sweet cookies'],
  ['candy', 'a couple of wrapped candies'],
  ['gummies', 'colorful gummy candies'],
  ['sweets', 'an assortment of candy sweets'],
  ['peanuts', 'a small pile of peanuts'],
  ['almonds', 'a small pile of almonds'],
  ['walnuts', 'a few walnuts'],
  ['ibuprofen', 'a blister pack of pills'],
  ['paracetamol', 'a box of pills'],
  ['aspirin', 'a bottle of aspirin tablets'],
  ['bandAids', 'a couple of adhesive bandages'],
  ['alcohol', 'a bottle of rubbing alcohol'],
  ['cotton', 'a roll of cotton wool with a colored band'],
  ['cottonSwabs', 'a small box of cotton swabs'],
  ['tissues', 'a box of tissues with a colored design'],
  ['toothpaste', 'a tube of toothpaste with a colored cap'],
  ['shampoo', 'a bottle of shampoo with a colored body and label'],
  ['conditioner', 'a bottle of hair conditioner with a colored body'],
  ['bodyCream', 'a jar of body cream with a colored lid'],
  ['sunscreen', 'a bottle of sunscreen with an orange and blue label'],
  ['deodorant', 'a deodorant stick with a colored cap'],
  ['antiperspirant', 'an antiperspirant spray can with a colored label'],
  ['razor', 'a shaving razor with a colored handle'],
  ['barSoap', 'a bar of soap with a colored tone'],
  ['liners', 'a pack of panty liners'],
  ['pads', 'a pack of sanitary pads'],
  ['condoms', 'a box of condoms'],
  ['dogFood', 'a bag of dog food with a paw print'],
  ['catFood', 'a bag of cat food with a paw print'],
  ['catStones', 'a bag of cat litter stones'],
  ['catLitter', 'a bag of cat litter'],
  ['petTreats', 'a box of pet treats'],
  ['petBags', 'a roll of pet waste bags'],
  ['frozenFries', 'a bag of frozen french fries with fries showing, frosty blue tones'],
  ['frozenVegetables', 'a bag of frozen mixed vegetables with veggies showing, frosty tones'],
  ['frozenFish', 'a pack of frozen fish fillets with frosty blue tones'],
  ['nuggets', 'a few golden chicken nuggets'],
  ['ice', 'a small pile of blue-tinted ice cubes'],
  ['oil', 'a bottle of golden cooking oil with a colored cap'],
  ['vinegar', 'a bottle of vinegar with a colored label and cap'],
  ['salt', 'a salt shaker with a colored cap'],
  ['pepperSpice', 'a pepper shaker with a colored cap'],
  ['seasonings', 'a jar of mixed seasonings with a colored lid'],
  ['sugar', 'a bowl of white sugar with a small spoon'],
  ['sweetener', 'a small box of sweetener with colored packets'],
  ['pasta', 'a bundle of spaghetti pasta tied with a band'],
  ['rice', 'a bowl of cooked white rice with a few grains, clearly rice'],
  ['flour', 'a bowl of flour with a small pile and a wheat accent'],
  ['polenta', 'a bowl of yellow polenta cornmeal'],
  ['oats', 'a bowl of oats with a wooden spoon'],
  ['lentils', 'a small bowl of orange lentils'],
  ['chickpeas', 'a small bowl of chickpeas'],
  ['beans', 'a small bowl of beans'],
  ['peas', 'a small bowl of green peas'],
  ['coffee', 'a cup of coffee with a few coffee beans next to it'],
  ['cocoa', 'a tin of cocoa powder with a brown label'],
  ['yerbaMate', 'a mate gourd with a metal straw (bombilla)'],
  ['tea', 'a box of tea bags with a tea cup'],
  ['tuna', 'an open tin can of tuna showing the fish inside'],
  ['tomatoSauce', 'a can of tomato sauce'],
  ['soySauce', 'a bottle of soy sauce'],
  ['ketchup', 'a bottle of ketchup'],
  ['mayonnaise', 'a jar of mayonnaise with a blue lid'],
  ['mustard', 'a squeeze bottle of yellow mustard'],
  ['jam', 'a jar of red fruit jam with a colored lid'],
  ['bakingChocolate', 'a bar of dark baking chocolate'],
  ['gelatin', 'a bowl of red fruit gelatin dessert'],
];

module.exports = { catalog };
