// Catálogo de productos -> frase en inglés para el generador de imágenes.
// Fuente: flutter_client/lib/features/shopping/utils/shopping_localization.dart
// La "key" debe coincidir EXACTO con la del catálogo (así el manifest matchea).
// El "noun" es la descripción del objeto a dibujar (afinada para items argentinos).

const catalog = [
  ['tomato', 'a ripe red tomato'],
  ['onion', 'a brown onion'],
  ['greenOnion', 'a bunch of green onions (scallions)'],
  ['potato', 'a potato'],
  ['apple', 'a red apple with a small green leaf'],
  ['banana', 'a ripe yellow banana'],
  ['pear', 'a green pear'],
  ['peach', 'a peach'],
  ['lemon', 'a yellow lemon with a leaf'],
  ['orange', 'an orange fruit with a leaf'],
  ['tangerine', 'a peeled-friendly mandarin orange'],
  ['grapefruit', 'a grapefruit cut showing pink flesh'],
  ['kiwi', 'a kiwi fruit sliced in half'],
  ['pineapple', 'a pineapple'],
  ['strawberry', 'a strawberry'],
  ['grapes', 'a bunch of purple grapes'],
  ['watermelon', 'a slice of watermelon'],
  ['carrot', 'a carrot with green leafy top'],
  ['garlic', 'a head of garlic'],
  ['ginger', 'a ginger root'],
  ['lettuce', 'a head of green lettuce'],
  ['arugula', 'a small bunch of arugula leaves'],
  ['spinach', 'a bunch of spinach leaves'],
  ['chard', 'a bunch of swiss chard'],
  ['celery', 'a celery stalk bunch'],
  ['avocado', 'an avocado cut in half with the pit'],
  ['bellPepper', 'a red bell pepper'],
  ['pepper', 'a green chili pepper'],
  ['pumpkin', 'an orange pumpkin squash'],
  ['sweetPotato', 'a sweet potato'],
  ['boniato', 'a sweet potato'],
  ['broccoli', 'a broccoli floret'],
  ['eggplant', 'a purple eggplant'],
  ['mushrooms', 'two button mushrooms'],
  ['corn', 'an ear of corn with husk leaves'],
  ['cucumber', 'a cucumber'],
  ['beet', 'a red beetroot with leaves'],
  ['groundBeef', 'a portion of ground beef'],
  ['chicken', 'a raw chicken drumstick'],
  ['fish', 'a whole fresh fish'],
  ['pork', 'a cut of pork meat'],
  ['bondiola', 'a cut of pork shoulder'],
  ['flankSteak', 'a cut of beef flank steak'],
  ['matambre', 'a thin rolled beef cut'],
  ['peceto', 'a round beef roast cut'],
  ['ribs', 'a rack of beef ribs'],
  ['milanesas', 'a breaded meat cutlet (milanesa)'],
  ['sausages', 'a pair of sausages'],
  ['chorizo', 'a chorizo sausage'],
  ['burgers', 'two raw burger patties'],
  ['bacon', 'strips of bacon'],
  ['milk', 'a carton of milk'],
  ['plantMilk', 'a carton of plant-based milk with a leaf'],
  ['condensedMilk', 'a can of condensed milk'],
  ['chocolateMilk', 'a carton of chocolate milk'],
  ['freshCheese', 'a block of fresh white cheese'],
  ['gratedCheese', 'a bag of grated cheese'],
  ['creamCheese', 'a tub of cream cheese'],
  ['provolone', 'a wheel of provolone cheese'],
  ['mozzarella', 'a ball of mozzarella cheese'],
  ['butter', 'a stick of butter'],
  ['cream', 'a small carton of cream'],
  ['yogurt', 'a cup of yogurt'],
  ['drinkableYogurt', 'a bottle of drinkable yogurt'],
  ['eggs', 'two eggs, one with a yolk'],
  ['dulceDeLeche', 'a jar of dulce de leche caramel spread'],
  ['tofu', 'a block of tofu'],
  ['hummus', 'a bowl of hummus'],
  ['bread', 'a loaf of bread'],
  ['sandwichBread', 'a loaf of sliced sandwich bread'],
  ['breadcrumbs', 'a bag of breadcrumbs'],
  ['toast', 'two slices of toast'],
  ['croissants', 'two croissants'],
  ['criollos', 'criollo pastry biscuits'],
  ['biscuits', 'a stack of plain biscuits'],
  ['ladyfingers', 'ladyfinger biscuits'],
  ['cookies', 'a few round cookies'],
  ['tart', 'a savory tart pie'],
  ['detergent', 'a bottle of dish detergent'],
  ['bleach', 'a bottle of bleach'],
  ['glassCleaner', 'a spray bottle of glass cleaner'],
  ['floorCleaner', 'a bottle of floor cleaner'],
  ['multipurposeCleaner', 'a spray bottle of multi-purpose cleaner'],
  ['degreaser', 'a spray bottle of degreaser'],
  ['disinfectant', 'a bottle of disinfectant'],
  ['insecticide', 'an aerosol can of insecticide'],
  ['toiletPaper', 'a roll of toilet paper'],
  ['kitchenRoll', 'a roll of paper towels'],
  ['sponge', 'a cleaning sponge'],
  ['dishcloth', 'a folded cleaning cloth'],
  ['broom', 'a broom'],
  ['laundrySoap', 'a box of laundry detergent'],
  ['softener', 'a bottle of fabric softener'],
  ['bags', 'a roll of plastic bags'],
  ['water', 'a bottle of water'],
  ['flavoredWater', 'a bottle of flavored water'],
  ['sparklingWater', 'a soda siphon bottle'],
  ['tonicWater', 'a bottle of tonic water'],
  ['soda', 'a bottle of soft drink soda'],
  ['cocaCola', 'a glass bottle of cola soft drink'],
  ['juice', 'a carton of fruit juice with a straw'],
  ['sportsDrink', 'a bottle of sports drink'],
  ['energyDrink', 'a can of energy drink'],
  ['beer', 'a bottle of beer'],
  ['wine', 'a bottle of red wine'],
  ['vermouth', 'a bottle of vermouth'],
  ['champagne', 'a bottle of champagne'],
  ['cider', 'a bottle of cider'],
  ['whisky', 'a bottle of whisky'],
  ['fernet', 'a dark bottle of fernet liquor'],
  ['aperitif', 'a glass of orange aperitif drink'],
  ['terma', 'a bottle of herbal bitters drink'],
  ['chips', 'a bag of potato chips'],
  ['cheesePuffs', 'a bag of cheese puff snacks'],
  ['pretzelSticks', 'a handful of salted pretzel sticks'],
  ['popcorn', 'a bucket of popcorn'],
  ['chocolate', 'a chocolate bar'],
  ['turron', 'a nougat bar'],
  ['alfajor', 'an alfajor round cookie sandwich'],
  ['poundCake', 'a slice of pound cake'],
  ['iceCream', 'an ice cream tub'],
  ['sweetCookies', 'a pack of sweet cookies'],
  ['candy', 'a couple of wrapped candies'],
  ['gummies', 'colorful gummy candies'],
  ['sweets', 'an assortment of candy sweets'],
  ['peanuts', 'a small pile of peanuts'],
  ['almonds', 'a small pile of almonds'],
  ['walnuts', 'a few walnuts'],
  ['ibuprofen', 'a blister pack of pills'],
  ['paracetamol', 'a box of pills'],
  ['aspirin', 'a bottle of aspirin tablets'],
  ['bandAids', 'a couple of adhesive bandages'],
  ['alcohol', 'a bottle of rubbing alcohol'],
  ['cotton', 'a roll of cotton wool'],
  ['cottonSwabs', 'cotton swabs'],
  ['tissues', 'a box of tissues'],
  ['toothpaste', 'a tube of toothpaste'],
  ['shampoo', 'a bottle of shampoo'],
  ['conditioner', 'a bottle of hair conditioner'],
  ['bodyCream', 'a jar of body cream'],
  ['sunscreen', 'a bottle of sunscreen'],
  ['deodorant', 'a deodorant stick'],
  ['antiperspirant', 'an antiperspirant spray can'],
  ['razor', 'a shaving razor'],
  ['barSoap', 'a bar of soap'],
  ['liners', 'a pack of panty liners'],
  ['pads', 'a pack of sanitary pads'],
  ['condoms', 'a box of condoms'],
  ['dogFood', 'a bag of dog food with a paw print'],
  ['catFood', 'a bag of cat food with a paw print'],
  ['catStones', 'a bag of cat litter stones'],
  ['catLitter', 'a bag of cat litter'],
  ['petTreats', 'a box of pet treats'],
  ['petBags', 'a roll of pet waste bags'],
  ['frozenFries', 'a bag of frozen french fries'],
  ['frozenVegetables', 'a bag of frozen mixed vegetables'],
  ['frozenFish', 'a frozen fish fillet pack'],
  ['nuggets', 'a few chicken nuggets'],
  ['ice', 'ice cubes'],
  ['oil', 'a bottle of cooking oil'],
  ['vinegar', 'a bottle of vinegar'],
  ['salt', 'a salt shaker'],
  ['pepperSpice', 'a pepper shaker'],
  ['seasonings', 'a jar of mixed seasonings'],
  ['sugar', 'a bag of sugar'],
  ['sweetener', 'a small box of sweetener packets'],
  ['pasta', 'a bundle of spaghetti pasta'],
  ['rice', 'a bag of white rice'],
  ['flour', 'a bag of flour'],
  ['polenta', 'a bag of polenta cornmeal'],
  ['oats', 'a bowl of oats'],
  ['lentils', 'a small pile of lentils'],
  ['chickpeas', 'a small pile of chickpeas'],
  ['beans', 'a small pile of beans'],
  ['peas', 'a small pile of green peas'],
  ['coffee', 'a bag of coffee beans'],
  ['cocoa', 'a tin of cocoa powder'],
  ['yerbaMate', 'a pack of yerba mate'],
  ['tea', 'a box of tea bags'],
  ['tuna', 'a can of tuna'],
  ['tomatoSauce', 'a can of tomato sauce'],
  ['soySauce', 'a bottle of soy sauce'],
  ['ketchup', 'a bottle of ketchup'],
  ['mayonnaise', 'a jar of mayonnaise'],
  ['mustard', 'a bottle of mustard'],
  ['jam', 'a jar of fruit jam'],
  ['bakingChocolate', 'a bar of baking chocolate'],
  ['gelatin', 'a bowl of fruit gelatin dessert'],
];

module.exports = { catalog };
