import 'package:flutter/foundation.dart';
import 'package:homesync_client/l10n/generated/app_localizations.dart';

@immutable
class CoupleChallenge {
  final String id;
  final String icon;
  final int coinReward;

  const CoupleChallenge({
    required this.id,
    required this.icon,
    required this.coinReward,
  });

  static CoupleChallenge get testChallenge => allChallenges[0];

  static const List<CoupleChallenge> allChallenges = [
    CoupleChallenge(id: 'weekly_challenge_1', icon: '❤️', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_2', icon: '🕯️', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_3', icon: '✨', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_4', icon: '🎤', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_5', icon: '🎨', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_6', icon: '🍿', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_7', icon: '📸', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_8', icon: '🧺', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_9', icon: '✉️', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_10', icon: '📵', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_11', icon: '🏺', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_23', icon: '🥐', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_24', icon: '🌊', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_25', icon: '🧭', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_26', icon: '🔥', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_27', icon: '🎁', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_28', icon: '💝', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_29', icon: '🎭', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_30', icon: '🍷', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_31', icon: '🛌', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_32', icon: '🥬', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_33', icon: '🌌', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_34', icon: '👂', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_35', icon: '📖', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_36', icon: '🎟️', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_37', icon: '✈️', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_38', icon: '✉️', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_39', icon: '🌄', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_40', icon: '🧩', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_41', icon: '🙏', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_42', icon: '📦', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_43', icon: '🙈', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_44', icon: '🎙️', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_45', icon: '⏳', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_46', icon: '🎞️', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_47', icon: '✅', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_48', icon: '🥂', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_49', icon: '🍳', coinReward: 15),
    CoupleChallenge(id: 'weekly_challenge_50', icon: '🖼️', coinReward: 15),
  ];

  static CoupleChallenge currentWeeklyChallenge(
      [DateTime? householdCreatedAt,]) {
    final index = currentWeeklyChallengeIndex(householdCreatedAt);
    return allChallenges[index];
  }

  static int currentWeeklyChallengeIndex([DateTime? householdCreatedAt]) {
    if (householdCreatedAt == null) return 0;
    final difference = DateTime.now().difference(householdCreatedAt);
    final weekIndex = (difference.inDays / 7).floor();
    if (weekIndex < 0) return 0;
    return weekIndex % allChallenges.length;
  }
}

extension CoupleChallengeL10n on CoupleChallenge {
  String localizedTitle(AppLocalizations t) => switch (id) {
        'weekly_challenge_1' => t.coupleChallenge1Title,
        'weekly_challenge_2' => t.coupleChallenge2Title,
        'weekly_challenge_3' => t.coupleChallenge3Title,
        'weekly_challenge_4' => t.coupleChallenge4Title,
        'weekly_challenge_5' => t.coupleChallenge5Title,
        'weekly_challenge_6' => t.coupleChallenge6Title,
        'weekly_challenge_7' => t.coupleChallenge7Title,
        'weekly_challenge_8' => t.coupleChallenge8Title,
        'weekly_challenge_9' => t.coupleChallenge9Title,
        'weekly_challenge_10' => t.coupleChallenge10Title,
        'weekly_challenge_11' => t.coupleChallenge11Title,
        'weekly_challenge_23' => t.coupleChallenge23Title,
        'weekly_challenge_24' => t.coupleChallenge24Title,
        'weekly_challenge_25' => t.coupleChallenge25Title,
        'weekly_challenge_26' => t.coupleChallenge26Title,
        'weekly_challenge_27' => t.coupleChallenge27Title,
        'weekly_challenge_28' => t.coupleChallenge28Title,
        'weekly_challenge_29' => t.coupleChallenge29Title,
        'weekly_challenge_30' => t.coupleChallenge30Title,
        'weekly_challenge_31' => t.coupleChallenge31Title,
        'weekly_challenge_32' => t.coupleChallenge32Title,
        'weekly_challenge_33' => t.coupleChallenge33Title,
        'weekly_challenge_34' => t.coupleChallenge34Title,
        'weekly_challenge_35' => t.coupleChallenge35Title,
        'weekly_challenge_36' => t.coupleChallenge36Title,
        'weekly_challenge_37' => t.coupleChallenge37Title,
        'weekly_challenge_38' => t.coupleChallenge38Title,
        'weekly_challenge_39' => t.coupleChallenge39Title,
        'weekly_challenge_40' => t.coupleChallenge40Title,
        'weekly_challenge_41' => t.coupleChallenge41Title,
        'weekly_challenge_42' => t.coupleChallenge42Title,
        'weekly_challenge_43' => t.coupleChallenge43Title,
        'weekly_challenge_44' => t.coupleChallenge44Title,
        'weekly_challenge_45' => t.coupleChallenge45Title,
        'weekly_challenge_46' => t.coupleChallenge46Title,
        'weekly_challenge_47' => t.coupleChallenge47Title,
        'weekly_challenge_48' => t.coupleChallenge48Title,
        'weekly_challenge_49' => t.coupleChallenge49Title,
        'weekly_challenge_50' => t.coupleChallenge50Title,
        _ => id,
      };

  String localizedDescription(AppLocalizations t) => switch (id) {
        'weekly_challenge_1' => t.coupleChallenge1Description,
        'weekly_challenge_2' => t.coupleChallenge2Description,
        'weekly_challenge_3' => t.coupleChallenge3Description,
        'weekly_challenge_4' => t.coupleChallenge4Description,
        'weekly_challenge_5' => t.coupleChallenge5Description,
        'weekly_challenge_6' => t.coupleChallenge6Description,
        'weekly_challenge_7' => t.coupleChallenge7Description,
        'weekly_challenge_8' => t.coupleChallenge8Description,
        'weekly_challenge_9' => t.coupleChallenge9Description,
        'weekly_challenge_10' => t.coupleChallenge10Description,
        'weekly_challenge_11' => t.coupleChallenge11Description,
        'weekly_challenge_23' => t.coupleChallenge23Description,
        'weekly_challenge_24' => t.coupleChallenge24Description,
        'weekly_challenge_25' => t.coupleChallenge25Description,
        'weekly_challenge_26' => t.coupleChallenge26Description,
        'weekly_challenge_27' => t.coupleChallenge27Description,
        'weekly_challenge_28' => t.coupleChallenge28Description,
        'weekly_challenge_29' => t.coupleChallenge29Description,
        'weekly_challenge_30' => t.coupleChallenge30Description,
        'weekly_challenge_31' => t.coupleChallenge31Description,
        'weekly_challenge_32' => t.coupleChallenge32Description,
        'weekly_challenge_33' => t.coupleChallenge33Description,
        'weekly_challenge_34' => t.coupleChallenge34Description,
        'weekly_challenge_35' => t.coupleChallenge35Description,
        'weekly_challenge_36' => t.coupleChallenge36Description,
        'weekly_challenge_37' => t.coupleChallenge37Description,
        'weekly_challenge_38' => t.coupleChallenge38Description,
        'weekly_challenge_39' => t.coupleChallenge39Description,
        'weekly_challenge_40' => t.coupleChallenge40Description,
        'weekly_challenge_41' => t.coupleChallenge41Description,
        'weekly_challenge_42' => t.coupleChallenge42Description,
        'weekly_challenge_43' => t.coupleChallenge43Description,
        'weekly_challenge_44' => t.coupleChallenge44Description,
        'weekly_challenge_45' => t.coupleChallenge45Description,
        'weekly_challenge_46' => t.coupleChallenge46Description,
        'weekly_challenge_47' => t.coupleChallenge47Description,
        'weekly_challenge_48' => t.coupleChallenge48Description,
        'weekly_challenge_49' => t.coupleChallenge49Description,
        'weekly_challenge_50' => t.coupleChallenge50Description,
        _ => '',
      };

  String localizedCategory(AppLocalizations t) => switch (id) {
        'weekly_challenge_1' => t.coupleChallenge1Category,
        'weekly_challenge_2' => t.coupleChallenge2Category,
        'weekly_challenge_3' => t.coupleChallenge3Category,
        'weekly_challenge_4' => t.coupleChallenge4Category,
        'weekly_challenge_5' => t.coupleChallenge5Category,
        'weekly_challenge_6' => t.coupleChallenge6Category,
        'weekly_challenge_7' => t.coupleChallenge7Category,
        'weekly_challenge_8' => t.coupleChallenge8Category,
        'weekly_challenge_9' => t.coupleChallenge9Category,
        'weekly_challenge_10' => t.coupleChallenge10Category,
        'weekly_challenge_11' => t.coupleChallenge11Category,
        'weekly_challenge_23' => t.coupleChallenge23Category,
        'weekly_challenge_24' => t.coupleChallenge24Category,
        'weekly_challenge_25' => t.coupleChallenge25Category,
        'weekly_challenge_26' => t.coupleChallenge26Category,
        'weekly_challenge_27' => t.coupleChallenge27Category,
        'weekly_challenge_28' => t.coupleChallenge28Category,
        'weekly_challenge_29' => t.coupleChallenge29Category,
        'weekly_challenge_30' => t.coupleChallenge30Category,
        'weekly_challenge_31' => t.coupleChallenge31Category,
        'weekly_challenge_32' => t.coupleChallenge32Category,
        'weekly_challenge_33' => t.coupleChallenge33Category,
        'weekly_challenge_34' => t.coupleChallenge34Category,
        'weekly_challenge_35' => t.coupleChallenge35Category,
        'weekly_challenge_36' => t.coupleChallenge36Category,
        'weekly_challenge_37' => t.coupleChallenge37Category,
        'weekly_challenge_38' => t.coupleChallenge38Category,
        'weekly_challenge_39' => t.coupleChallenge39Category,
        'weekly_challenge_40' => t.coupleChallenge40Category,
        'weekly_challenge_41' => t.coupleChallenge41Category,
        'weekly_challenge_42' => t.coupleChallenge42Category,
        'weekly_challenge_43' => t.coupleChallenge43Category,
        'weekly_challenge_44' => t.coupleChallenge44Category,
        'weekly_challenge_45' => t.coupleChallenge45Category,
        'weekly_challenge_46' => t.coupleChallenge46Category,
        'weekly_challenge_47' => t.coupleChallenge47Category,
        'weekly_challenge_48' => t.coupleChallenge48Category,
        'weekly_challenge_49' => t.coupleChallenge49Category,
        'weekly_challenge_50' => t.coupleChallenge50Category,
        _ => '',
      };

  String localizedLocation(AppLocalizations t) => switch (id) {
        'weekly_challenge_1' => t.coupleChallenge1Location,
        'weekly_challenge_2' => t.coupleChallenge2Location,
        'weekly_challenge_3' => t.coupleChallenge3Location,
        'weekly_challenge_4' => t.coupleChallenge4Location,
        'weekly_challenge_5' => t.coupleChallenge5Location,
        'weekly_challenge_6' => t.coupleChallenge6Location,
        'weekly_challenge_7' => t.coupleChallenge7Location,
        'weekly_challenge_8' => t.coupleChallenge8Location,
        'weekly_challenge_9' => t.coupleChallenge9Location,
        'weekly_challenge_10' => t.coupleChallenge10Location,
        'weekly_challenge_11' => t.coupleChallenge11Location,
        'weekly_challenge_23' => t.coupleChallenge23Location,
        'weekly_challenge_24' => t.coupleChallenge24Location,
        'weekly_challenge_25' => t.coupleChallenge25Location,
        'weekly_challenge_26' => t.coupleChallenge26Location,
        'weekly_challenge_27' => t.coupleChallenge27Location,
        'weekly_challenge_28' => t.coupleChallenge28Location,
        'weekly_challenge_29' => t.coupleChallenge29Location,
        'weekly_challenge_30' => t.coupleChallenge30Location,
        'weekly_challenge_31' => t.coupleChallenge31Location,
        'weekly_challenge_32' => t.coupleChallenge32Location,
        'weekly_challenge_33' => t.coupleChallenge33Location,
        'weekly_challenge_34' => t.coupleChallenge34Location,
        'weekly_challenge_35' => t.coupleChallenge35Location,
        'weekly_challenge_36' => t.coupleChallenge36Location,
        'weekly_challenge_37' => t.coupleChallenge37Location,
        'weekly_challenge_38' => t.coupleChallenge38Location,
        'weekly_challenge_39' => t.coupleChallenge39Location,
        'weekly_challenge_40' => t.coupleChallenge40Location,
        'weekly_challenge_41' => t.coupleChallenge41Location,
        'weekly_challenge_42' => t.coupleChallenge42Location,
        'weekly_challenge_43' => t.coupleChallenge43Location,
        'weekly_challenge_44' => t.coupleChallenge44Location,
        'weekly_challenge_45' => t.coupleChallenge45Location,
        'weekly_challenge_46' => t.coupleChallenge46Location,
        'weekly_challenge_47' => t.coupleChallenge47Location,
        'weekly_challenge_48' => t.coupleChallenge48Location,
        'weekly_challenge_49' => t.coupleChallenge49Location,
        'weekly_challenge_50' => t.coupleChallenge50Location,
        _ => '',
      };

  String localizedTiming(AppLocalizations t) => switch (id) {
        'weekly_challenge_1' => t.coupleChallenge1Timing,
        'weekly_challenge_2' => t.coupleChallenge2Timing,
        'weekly_challenge_3' => t.coupleChallenge3Timing,
        'weekly_challenge_4' => t.coupleChallenge4Timing,
        'weekly_challenge_5' => t.coupleChallenge5Timing,
        'weekly_challenge_6' => t.coupleChallenge6Timing,
        'weekly_challenge_7' => t.coupleChallenge7Timing,
        'weekly_challenge_8' => t.coupleChallenge8Timing,
        'weekly_challenge_9' => t.coupleChallenge9Timing,
        'weekly_challenge_10' => t.coupleChallenge10Timing,
        'weekly_challenge_11' => t.coupleChallenge11Timing,
        'weekly_challenge_23' => t.coupleChallenge23Timing,
        'weekly_challenge_24' => t.coupleChallenge24Timing,
        'weekly_challenge_25' => t.coupleChallenge25Timing,
        'weekly_challenge_26' => t.coupleChallenge26Timing,
        'weekly_challenge_27' => t.coupleChallenge27Timing,
        'weekly_challenge_28' => t.coupleChallenge28Timing,
        'weekly_challenge_29' => t.coupleChallenge29Timing,
        'weekly_challenge_30' => t.coupleChallenge30Timing,
        'weekly_challenge_31' => t.coupleChallenge31Timing,
        'weekly_challenge_32' => t.coupleChallenge32Timing,
        'weekly_challenge_33' => t.coupleChallenge33Timing,
        'weekly_challenge_34' => t.coupleChallenge34Timing,
        'weekly_challenge_35' => t.coupleChallenge35Timing,
        'weekly_challenge_36' => t.coupleChallenge36Timing,
        'weekly_challenge_37' => t.coupleChallenge37Timing,
        'weekly_challenge_38' => t.coupleChallenge38Timing,
        'weekly_challenge_39' => t.coupleChallenge39Timing,
        'weekly_challenge_40' => t.coupleChallenge40Timing,
        'weekly_challenge_41' => t.coupleChallenge41Timing,
        'weekly_challenge_42' => t.coupleChallenge42Timing,
        'weekly_challenge_43' => t.coupleChallenge43Timing,
        'weekly_challenge_44' => t.coupleChallenge44Timing,
        'weekly_challenge_45' => t.coupleChallenge45Timing,
        'weekly_challenge_46' => t.coupleChallenge46Timing,
        'weekly_challenge_47' => t.coupleChallenge47Timing,
        'weekly_challenge_48' => t.coupleChallenge48Timing,
        'weekly_challenge_49' => t.coupleChallenge49Timing,
        'weekly_challenge_50' => t.coupleChallenge50Timing,
        _ => '',
      };

  String localizedMotivation(AppLocalizations t) => switch (id) {
        'weekly_challenge_1' => t.coupleChallenge1Motivation,
        'weekly_challenge_2' => t.coupleChallenge2Motivation,
        'weekly_challenge_3' => t.coupleChallenge3Motivation,
        'weekly_challenge_4' => t.coupleChallenge4Motivation,
        'weekly_challenge_5' => t.coupleChallenge5Motivation,
        'weekly_challenge_6' => t.coupleChallenge6Motivation,
        'weekly_challenge_7' => t.coupleChallenge7Motivation,
        'weekly_challenge_8' => t.coupleChallenge8Motivation,
        'weekly_challenge_9' => t.coupleChallenge9Motivation,
        'weekly_challenge_10' => t.coupleChallenge10Motivation,
        'weekly_challenge_11' => t.coupleChallenge11Motivation,
        'weekly_challenge_23' => t.coupleChallenge23Motivation,
        'weekly_challenge_24' => t.coupleChallenge24Motivation,
        'weekly_challenge_25' => t.coupleChallenge25Motivation,
        'weekly_challenge_26' => t.coupleChallenge26Motivation,
        'weekly_challenge_27' => t.coupleChallenge27Motivation,
        'weekly_challenge_28' => t.coupleChallenge28Motivation,
        'weekly_challenge_29' => t.coupleChallenge29Motivation,
        'weekly_challenge_30' => t.coupleChallenge30Motivation,
        'weekly_challenge_31' => t.coupleChallenge31Motivation,
        'weekly_challenge_32' => t.coupleChallenge32Motivation,
        'weekly_challenge_33' => t.coupleChallenge33Motivation,
        'weekly_challenge_34' => t.coupleChallenge34Motivation,
        'weekly_challenge_35' => t.coupleChallenge35Motivation,
        'weekly_challenge_36' => t.coupleChallenge36Motivation,
        'weekly_challenge_37' => t.coupleChallenge37Motivation,
        'weekly_challenge_38' => t.coupleChallenge38Motivation,
        'weekly_challenge_39' => t.coupleChallenge39Motivation,
        'weekly_challenge_40' => t.coupleChallenge40Motivation,
        'weekly_challenge_41' => t.coupleChallenge41Motivation,
        'weekly_challenge_42' => t.coupleChallenge42Motivation,
        'weekly_challenge_43' => t.coupleChallenge43Motivation,
        'weekly_challenge_44' => t.coupleChallenge44Motivation,
        'weekly_challenge_45' => t.coupleChallenge45Motivation,
        'weekly_challenge_46' => t.coupleChallenge46Motivation,
        'weekly_challenge_47' => t.coupleChallenge47Motivation,
        'weekly_challenge_48' => t.coupleChallenge48Motivation,
        'weekly_challenge_49' => t.coupleChallenge49Motivation,
        'weekly_challenge_50' => t.coupleChallenge50Motivation,
        _ => '',
      };
}
