// Mocks generated by Mockito 5.4.6 from annotations
// in homesync_client/test/tasks_flow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:homesync_client/features/tasks/domain/models/task_model.dart'
    as _i4;
import 'package:homesync_client/features/tasks/domain/repositories/task_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i2.TaskRepository {
  MockTaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.TaskModel>> getTasks(
    String? householdId, {
    int? limit = 100,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasks,
          [householdId],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i3.Future<List<_i4.TaskModel>>.value(<_i4.TaskModel>[]),
      ) as _i3.Future<List<_i4.TaskModel>>);

  @override
  _i3.Future<Map<String, dynamic>> completeTask(
    _i4.TaskModel? task, {
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeTask,
          [task],
          {#userId: userId},
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> verifyTask(
    String? taskId,
    String? verifiedByUserId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyTask,
          [
            taskId,
            verifiedByUserId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> objectTask(
    String? taskId,
    String? objectedByUserId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #objectTask,
          [
            taskId,
            objectedByUserId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTask(String? taskId) => (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [taskId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateSchedule(
    String? taskId,
    String? recurrenceType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSchedule,
          [
            taskId,
            recurrenceType,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> createTask({
    required String? title,
    String? description,
    required String? category,
    required String? difficulty,
    required int? xpReward,
    required int? coinReward,
    String? assignedTo,
    String? recurrenceType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTask,
          [],
          {
            #title: title,
            #description: description,
            #category: category,
            #difficulty: difficulty,
            #xpReward: xpReward,
            #coinReward: coinReward,
            #assignedTo: assignedTo,
            #recurrenceType: recurrenceType,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> editTask(
    String? taskId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editTask,
          [
            taskId,
            updates,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
