// Mocks generated by Mockito 5.4.6 from annotations
// in homesync_client/test/tasks_flow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:homesync_client/core/errors/failures.dart' as _i5;
import 'package:homesync_client/core/models/task_completion_result.dart' as _i8;
import 'package:homesync_client/features/tasks/domain/models/task_model.dart'
    as _i6;
import 'package:homesync_client/features/tasks/domain/repositories/task_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i2.TaskRepository {
  MockTaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.TaskModel>>> getTasks(
    String? householdId, {
    int? limit = 100,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasks,
          [householdId],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.Failure, List<_i6.TaskModel>>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, List<_i6.TaskModel>>>(
          this,
          Invocation.method(
            #getTasks,
            [householdId],
            {
              #limit: limit,
              #offset: offset,
            },
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, List<_i6.TaskModel>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i8.TaskCompletionResult>> completeTask(
    _i6.TaskModel? task, {
    List<String>? userIds,
    DateTime? completedAt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeTask,
          [task],
          {
            #userIds: userIds,
            #completedAt: completedAt,
          },
        ),
        returnValue: _i3
            .Future<_i4.Either<_i5.Failure, _i8.TaskCompletionResult>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, _i8.TaskCompletionResult>>(
          this,
          Invocation.method(
            #completeTask,
            [task],
            {
              #userIds: userIds,
              #completedAt: completedAt,
            },
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i8.TaskCompletionResult>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, Map<String, dynamic>>> completeTasksBatch(
    List<_i6.TaskModel>? tasks, {
    List<String>? userIds,
    DateTime? completedAt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeTasksBatch,
          [tasks],
          {
            #userIds: userIds,
            #completedAt: completedAt,
          },
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.Failure, Map<String, dynamic>>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, Map<String, dynamic>>>(
          this,
          Invocation.method(
            #completeTasksBatch,
            [tasks],
            {
              #userIds: userIds,
              #completedAt: completedAt,
            },
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> verifyTask(
    String? taskId,
    String? verifiedByUserId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyTask,
          [
            taskId,
            verifiedByUserId,
          ],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
          this,
          Invocation.method(
            #verifyTask,
            [
              taskId,
              verifiedByUserId,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> objectTask(
    String? taskId,
    String? objectedByUserId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #objectTask,
          [
            taskId,
            objectedByUserId,
          ],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
          this,
          Invocation.method(
            #objectTask,
            [
              taskId,
              objectedByUserId,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> deleteTask(String? taskId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [taskId],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
          this,
          Invocation.method(
            #deleteTask,
            [taskId],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> updateSchedule(
    String? taskId,
    String? recurrenceType, {
    int? recurrenceInterval,
    List<int>? recurrenceWeekdays,
    List<int>? recurrenceMonthDays,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSchedule,
          [
            taskId,
            recurrenceType,
          ],
          {
            #recurrenceInterval: recurrenceInterval,
            #recurrenceWeekdays: recurrenceWeekdays,
            #recurrenceMonthDays: recurrenceMonthDays,
          },
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
          this,
          Invocation.method(
            #updateSchedule,
            [
              taskId,
              recurrenceType,
            ],
            {
              #recurrenceInterval: recurrenceInterval,
              #recurrenceWeekdays: recurrenceWeekdays,
              #recurrenceMonthDays: recurrenceMonthDays,
            },
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> createTask({
    required String? title,
    String? description,
    required String? category,
    required String? difficulty,
    required int? xpReward,
    required int? coinReward,
    String? assignedTo,
    String? recurrenceType,
    int? recurrenceInterval,
    List<int>? recurrenceWeekdays,
    List<int>? recurrenceMonthDays,
    String? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTask,
          [],
          {
            #title: title,
            #description: description,
            #category: category,
            #difficulty: difficulty,
            #xpReward: xpReward,
            #coinReward: coinReward,
            #assignedTo: assignedTo,
            #recurrenceType: recurrenceType,
            #recurrenceInterval: recurrenceInterval,
            #recurrenceWeekdays: recurrenceWeekdays,
            #recurrenceMonthDays: recurrenceMonthDays,
            #status: status,
          },
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
          this,
          Invocation.method(
            #createTask,
            [],
            {
              #title: title,
              #description: description,
              #category: category,
              #difficulty: difficulty,
              #xpReward: xpReward,
              #coinReward: coinReward,
              #assignedTo: assignedTo,
              #recurrenceType: recurrenceType,
              #recurrenceInterval: recurrenceInterval,
              #recurrenceWeekdays: recurrenceWeekdays,
              #recurrenceMonthDays: recurrenceMonthDays,
              #status: status,
            },
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> editTask(
    String? taskId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editTask,
          [
            taskId,
            updates,
          ],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
          this,
          Invocation.method(
            #editTask,
            [
              taskId,
              updates,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, Map<String, dynamic>>> undoTaskCompletion(
          String? activityId) =>
      (super.noSuchMethod(
        Invocation.method(
          #undoTaskCompletion,
          [activityId],
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.Failure, Map<String, dynamic>>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, Map<String, dynamic>>>(
          this,
          Invocation.method(
            #undoTaskCompletion,
            [activityId],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, Map<String, dynamic>>>);
}
