include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: false
    strict-raw-types: false
  errors:
    avoid_print: error
    unused_import: error
    unnecessary_import: error

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    avoid_dynamic_calls: true
    require_trailing_commas: true
    directives_ordering: true
    prefer_single_quotes: true
