-- Backfill savings contribution attribution from the matching ledger expense.
--
-- Early shared goal contributions stored the linked expense correctly, but the
-- savings_contributions row stayed as `personal` with an empty participants
-- snapshot. Match only very-close writes generated by the app so personal
-- contributions remain untouched.
with matched as (
  select
    sc.id as contribution_id,
    e.split_type,
    participants.participants
  from public.savings_contributions sc
  join public.savings_goals sg on sg.id = sc.goal_id
  join lateral (
    select e.*
    from public.expenses e
    where e.household_id = sg.household_id
      and e.title = ('Ahorro: ' || sg.title)
      and e.amount = sc.amount
      and e.paid_by = sc.user_id
      and abs(extract(epoch from (e.created_at - sc.created_at))) <= 5
    order by abs(extract(epoch from (e.created_at - sc.created_at)))
    limit 1
  ) e on true
  join lateral (
    select jsonb_agg(
      jsonb_build_object(
        'user_id', es.user_id,
        'name', coalesce(nullif(trim(u.full_name), ''), split_part(u.email, '@', 1), 'Miembro'),
        'email', u.email,
        'avatar_url', u.avatar_url
      )
      order by es.user_id
    ) as participants
    from public.expense_splits es
    left join public.users u on u.id = es.user_id
    where es.expense_id = e.id
  ) participants on true
  where sc.split_type = 'personal'
    and jsonb_array_length(coalesce(sc.participants, '[]'::jsonb)) = 0
    and e.split_type <> 'personal'
    and jsonb_array_length(coalesce(participants.participants, '[]'::jsonb)) > 1
)
update public.savings_contributions sc
set
  split_type = matched.split_type,
  participants = matched.participants
from matched
where sc.id = matched.contribution_id;
